version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:todos@db:5432/todos
    depends_on:
      - db
